### PR TITLE
build new releases

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
I tried `gem install test-unit minitest` to try to fix the problem, but it didn't work. Haven't found anything else online.

Also, the choices for `sifdecode` and `cutest` have changed because some specific versions of gfortran and gcc were added to the list. Here's the fix:
```diff
diff --git a/cutest.rb b/cutest.rb
--- a/cutest.rb
+++ b/cutest.rb
@@ -52,8 +52,8 @@ class Cutest < Formula
     else
       machine = "pc64"
       arch = "lnx"
-      fcomp = (build.with? "pgi") ? "7" : "2"
-      ccomp = (build.with? "pgi") ? "6" : "4"
+      fcomp = (build.with? "pgi") ? "7" : "4"
+      ccomp = (build.with? "pgi") ? "6" : "7"
       Pathname.new("cutest.input").write <<-EOF.undent
         6
         2
diff --git a/sifdecode.rb b/sifdecode.rb
--- a/sifdecode.rb
+++ b/sifdecode.rb
@@ -35,7 +35,7 @@ class Sifdecode < Formula
     else
       machine = "pc64"
       arch = "lnx"
-      comp = (build.with? "pgi") ? "7" : "2"
+      comp = (build.with? "pgi") ? "7" : "4"
       Pathname.new("sifdecode.input").write <<-EOF.undent
         6
         2
```

**Comment by dpo** [comment]
Thanks! Does `brew test` work for you locally?

**Comment by abelsiqueira** [comment]
Yes, it works.

**Comment by dpo** [comment]
The issue seems to be with TravisCI. Merging this.

**Pull request merged**
